# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-31 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CoreDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.Core')),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.Core')),
            ],
        ),
        migrations.CreateModel(
            name='FrameworkDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.Framework')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.Framework')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.Stage'),
        ),
        migrations.AddField(
            model_name='frameworkdesc',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.Stage'),
        ),
        migrations.AddField(
            model_name='coredesc',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.Stage'),
        ),
    ]
