# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-01 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_auto_20180131_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coredesc',
            name='descriptor',
            field=models.TextField(verbose_name='descriptor'),
        ),
        migrations.AlterField(
            model_name='frameworkdesc',
            name='descriptor',
            field=models.TextField(verbose_name='descriptor'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.TextField(verbose_name='Indicator'),
        ),
    ]
